### ISSUE TITLE
Please delete all Python internal files and make new release

### ISSUE THREAD

**Issue by LinguList** [cldf-datasets/crossandean_morphology#2]
This repository contains all kinds of wrong files like __pycache__, which should be deleted. Also, this should not be added to the lexibank community, but rather to the cldf-datastes community, I think, so I rejected it from the lexibank collection now.

**Comment by FredericBlum** [comment]
I removed the pycache and added a gitignore. Were there any other python-internal files that I missed that need to be removed before creating an updated release?

Having the repository with cldf-datasets seems fitting.
